# Install latex, and the various packages used by the start_paper Makefile:
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gsl-bin libgsl0-dev
  - sudo apt-get install latexmk
  - sudo apt-get install latex-xcolor
addons:
    apt:
        packages:
            - texlive-generic-recommended
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - texlive-publishers
install:

before_script:
  - pip install --user cookiecutter
  - pip install --user mkauthlist
  - pip install --user nose

# Now make the PDF, and move it to the top level, ready for deployment.
script:
  - nosetests tests/
  - make -C doc/desc-0000-start_paper-intro
  - cp doc/desc-0000-start_paper-intro/desc-0000-start_paper-intro.pdf .

# Finally, if it's the master branch being updated, force-push the
# resulting PDF to an otherwise empty "pdf" branch:
after_success: |
    if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
        git checkout --orphan pdf
        git rm -rf .
        git add -f desc-0000-start_paper-intro.pdf
        git -c user.name='travis' -c user.email='travis' commit -m init
        git push -q -f https://drphilmarshall:$GITHUB_API_KEY@github.com/DarkEnergyScienceCollaboration/start_paper pdf
    fi
